module.exports = [
  // Ignore common build and dependency folders
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "dist/**",
      "out/**",
      "tests/**",
      "e2e/**",
      ".claude/**",
      "coverage/**", // generated by `npm run test:coverage`; gitignored but eslint still saw it
      // Same shape as coverage: written by `npx playwright test`, gitignored, and still linted.
      // The trace viewer bundle is vendored minified JS, so it fails `--max-warnings=0` on
      // unused variables — meaning anyone who ran the E2E suite locally could not then lint.
      "playwright-report/**",
      "test-results/**",
    ],
  },

  // TypeScript files
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parser: require("@typescript-eslint/parser"),
      parserOptions: {
        project: "./tsconfig.json",
        ecmaVersion: 2021,
        sourceType: "module",
      },
      globals: {},
    },
    plugins: {
      "@typescript-eslint": require("@typescript-eslint/eslint-plugin"),
      "react-hooks": require("eslint-plugin-react-hooks"),
      security: require("eslint-plugin-security"),
    },
    rules: {
      // Relaxed rules for existing codebase - can be tightened over time
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-undef": "off",
      "@typescript-eslint/no-explicit-any": ["warn"],
      "@typescript-eslint/explicit-module-boundary-types": ["off"],
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      // Security rules
      "security/detect-object-injection": "off",
      "security/detect-non-literal-fs-filename": "off",
      "security/detect-eval-with-expression": "error",
      "security/detect-no-csrf-before-method-override": "error",
      "security/detect-possible-timing-attacks": "warn",
      "security/detect-pseudoRandomBytes": "warn",
      "security/detect-unsafe-regex": "error",
      "security/detect-buffer-noassert": "error",
      "security/detect-child-process": "warn",
      "security/detect-new-buffer": "error",
      "security/detect-non-literal-regexp": "warn",
      "security/detect-non-literal-require": "warn",
    },
  },

  // ── CSRF guard for browser-side mutations ──────────────────────────────────
  //
  // `proxy.ts` rejects every non-public /api/* request using a state-changing method unless it
  // carries a matching `x-csrf-token` header, so a bare `fetch` with method POST/PUT/PATCH/
  // DELETE always 403s. That silently broke owner assignment, bank-movement confirmation,
  // notification mark-read, onboarding and demo init at once, because nothing flagged it.
  //
  // The selector deliberately keys off "has a `method` that is not a GET/HEAD/OPTIONS literal"
  // rather than matching mutating literals directly: a view that passed its method as a
  // variable (`method,`) was missed entirely by a literal-only search.
  {
    files: ["components/**/*.{ts,tsx}", "app/**/*.{ts,tsx}", "lib/**/*.{ts,tsx}"],
    ignores: [
      "app/api/**", // server-side route handlers — never traverse proxy.ts
      "**/*.test.{ts,tsx}",
      "**/*.spec.{ts,tsx}",
      "app/tenant-portal/**", // public per isPublicApiRoute(); token-authenticated
      "app/auth/mfa/**", // public per isPublicApiRoute()
      "lib/utils/api-client.ts", // the sanctioned wrapper that adds the header
    ],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          // Accepts either mechanism: the csrfHeaders() helper, or an explicit
          // "x-csrf-token" header property (the older hand-rolled pattern in settings-*.tsx).
          selector:
            "CallExpression[callee.name='fetch'] > ObjectExpression:has(Property[key.name='method']):not(:has(Property[key.name='method'][value.value=/^(GET|HEAD|OPTIONS)$/i])):not(:has(CallExpression[callee.name='csrfHeaders'])):not(:has(Property[key.value=/^x-csrf-token$/i]))",
          message:
            "State-changing fetch without a CSRF token — proxy.ts will reject this with 403. Use apiFetch() from @/lib/utils/api-client, or pass headers: csrfHeaders({ ... }).",
        },
      ],
    },
  },

  // JavaScript files
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
    },
    rules: {
      "no-unused-vars": "warn",
    },
  },
  // Test files: allow explicit `any` in tests to reduce churn
  {
    files: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
];
